"""initial

Revision ID: 0001
Revises:
Create Date: 2026-01-01 00:00:00
"""

from alembic import op
import sqlalchemy as sa

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("kanoons", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("slug", sa.String(64), nullable=False), sa.Column("name", sa.String(128), nullable=False), sa.Column("logo_url", sa.String(256)), sa.Column("contact_info", sa.JSON(), nullable=False), sa.Column("social_links", sa.JSON(), nullable=False), sa.Column("about_text", sa.Text(), nullable=False), sa.Column("rules_text", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_kanoons_slug", "kanoons", ["slug"], unique=True)
    op.create_table("users", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("kanoon_id", sa.Integer(), sa.ForeignKey("kanoons.id", ondelete="CASCADE"), nullable=False), sa.Column("email", sa.String(255), nullable=False), sa.Column("full_name", sa.String(120), nullable=False), sa.Column("password_hash", sa.String(255), nullable=False), sa.Column("role", sa.Enum("user", "admin", "superadmin", name="role"), nullable=False), sa.Column("willing_to_help", sa.Boolean(), nullable=False), sa.Column("help_domains", sa.JSON(), nullable=False), sa.Column("experience_text", sa.Text(), nullable=False), sa.Column("extra_notes", sa.Text(), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("last_login_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("email"))
    op.create_table("events", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("kanoon_id", sa.Integer(), sa.ForeignKey("kanoons.id", ondelete="CASCADE"), nullable=False), sa.Column("title", sa.String(255), nullable=False), sa.Column("description", sa.Text(), nullable=False), sa.Column("event_type", sa.Enum("FESTIVAL", "TRIP", "MARKET", name="eventtype"), nullable=False), sa.Column("state", sa.Enum("DRAFT", "ACTIVE", "CLOSED", "DONE", name="eventstate"), nullable=False), sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False), sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False), sa.Column("base_price", sa.Float(), nullable=False), sa.Column("subsidy_cap", sa.Float(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("halls", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("kanoon_id", sa.Integer(), sa.ForeignKey("kanoons.id", ondelete="CASCADE"), nullable=False), sa.Column("name", sa.String(120), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("seats", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("kanoon_id", sa.Integer(), sa.ForeignKey("kanoons.id", ondelete="CASCADE"), nullable=False), sa.Column("hall_id", sa.Integer(), sa.ForeignKey("halls.id", ondelete="CASCADE"), nullable=False), sa.Column("row_label", sa.String(16), nullable=False), sa.Column("col_number", sa.Integer(), nullable=False), sa.Column("seat_label", sa.String(32), nullable=False), sa.Column("price", sa.Float(), nullable=False), sa.Column("gender_restriction", sa.String(16), nullable=False), sa.Column("admin_blocked", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("hall_id", "seat_label", name="uq_hall_seat"))
    op.create_table("orders", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("kanoon_id", sa.Integer(), sa.ForeignKey("kanoons.id", ondelete="CASCADE"), nullable=False), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("event_id", sa.Integer(), sa.ForeignKey("events.id", ondelete="CASCADE"), nullable=False), sa.Column("status", sa.Enum("pending", "paid", "failed", name="orderstatus"), nullable=False), sa.Column("total_price", sa.Float(), nullable=False), sa.Column("subsidy_applied", sa.Float(), nullable=False), sa.Column("meta", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("seat_reservations", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("kanoon_id", sa.Integer(), sa.ForeignKey("kanoons.id", ondelete="CASCADE"), nullable=False), sa.Column("order_id", sa.Integer(), sa.ForeignKey("orders.id", ondelete="CASCADE"), nullable=False), sa.Column("seat_id", sa.Integer(), sa.ForeignKey("seats.id", ondelete="CASCADE"), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("market_booth_requests", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("kanoon_id", sa.Integer(), sa.ForeignKey("kanoons.id", ondelete="CASCADE"), nullable=False), sa.Column("event_id", sa.Integer(), sa.ForeignKey("events.id", ondelete="CASCADE"), nullable=False), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("quantity", sa.Integer(), nullable=False), sa.Column("day_count", sa.Integer()), sa.Column("main_seller", sa.JSON(), nullable=False), sa.Column("extra_sellers", sa.JSON(), nullable=False), sa.Column("terms_accepted", sa.Boolean(), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("gallery_items", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("kanoon_id", sa.Integer(), sa.ForeignKey("kanoons.id", ondelete="CASCADE"), nullable=False), sa.Column("event_id", sa.Integer(), sa.ForeignKey("events.id", ondelete="CASCADE"), nullable=False), sa.Column("file_url", sa.String(512), nullable=False), sa.Column("title", sa.String(255), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("reviews", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("kanoon_id", sa.Integer(), sa.ForeignKey("kanoons.id", ondelete="CASCADE"), nullable=False), sa.Column("event_id", sa.Integer(), sa.ForeignKey("events.id", ondelete="CASCADE"), nullable=False), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("rating", sa.Integer(), nullable=False), sa.Column("comment", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("audit_logs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("kanoon_id", sa.Integer(), nullable=False), sa.Column("actor_user_id", sa.Integer()), sa.Column("action", sa.String(100), nullable=False), sa.Column("detail", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))


def downgrade() -> None:
    for table in ["audit_logs","reviews","gallery_items","market_booth_requests","seat_reservations","orders","seats","halls","events","users","kanoons"]:
        op.drop_table(table)
